#include <stdio.h>
#include <math.h>
#include <malloc.h>
#include <string.h>
#include <stdlib.h>
#include <network.h>
#include <debug.h>
#include <gccore.h>
#include <ogcsys.h>
#include <wiiuse/wpad.h>
